quizzard:
  realm: quizzard
  app:
    clientId: quizzard-app
    redirectUrl: http://localhost:3000/*
  userRole: USER
  adminRole: ADMIN

spring:
  application:
    name: quizzard
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/quizzard
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/quizzard?authSource=admin

app:
  cors:
    allowed-origins: http://localhost:3000

jwt:
  auth:
    converter:
      resource-id: quizzard-app
      principal-attribute: preferred_username
