quizzard:
  realm: quizzard
  app:
    clientId: quizzard-app
    redirectUrl: http://localhost:3000/*
  userRole: USER
  adminRole: ADMIN

keycloak:
  serverUrl: http://localhost:8090
  realm: master
  username: admin
  password: admin
  clientId: admin-cli

server:
  port: 8081

spring:
  application:
    name: quizzard
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/quizzard
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  data:
    mongodb:
      database: quizzard
      uri: mongodb+srv://root:quizzard@quizzard.xdju2p2.mongodb.net/


app:
  cors:
    allowed-origins: http://localhost:3000

jwt:
  auth:
    converter:
      resource-id: quizzard-app
      principal-attribute: preferred_username

cloud:
  aws:
    credentials:
      access-key: AKIAQADSZ5DU5BK45YZD
      secret-key: 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